### ISSUE TITLE
Display issue on Chrome-based browsers

### ISSUE THREAD

**Issue by csterritt** [stephband/scribe#23]
The display looks fine on Safari, but the chord names have dots underneath them on Brave (and also Chromium, I believe) like this:
<img width="263" alt="Screenshot 2024-06-13 at 8 36 02 AM" src="https://github.com/stephband/scribe/assets/37917/3312aa4a-8ec2-4d4e-b168-3b1e9ed50076">

Don't think it's morse code :-)

This is on an M2 Mac Air, running Sonoma 14.5.

**Comment by stephband** [comment]
In a previous commit I switched chord symbols to use the `<abbr>` element. Apparently those have `text-decoration` dotted underline in Chrome's user agent styles. Fixed.

**Comment by csterritt** [comment]
Awesome, thanks!
